### ISSUE TITLE
"Loops", "Basic Conditionals", and "Variables" are not objects.

### ISSUE THREAD

**Issue by jamen** [JamenMarz/tldr.js#1]
All of the mentioned are in `OBJECTS.md`, although they're not objects.

**Comment by jamen** [comment]
Perhaps a new file, `STATEMENDS.md` for "Loops" and we can break down "Basic Conditionals" into "If", "Else", "Try", etc?

As far as "Variables" go,  should we should think of another file for assignment orientated things, or figure out how to categorize that in one of the existing?

**Comment by whaaaley** [comment]
They're not in `OBJECTS.md`, they're in `TLDR.md`, but yeah, separating into more sections is probably a good idea. If you can't separate something into a new page it's probably best to leave them in `TLDR.md`.
