### ISSUE TITLE
Reorganization?

### ISSUE THREAD

**Issue by jamen** [JamenMarz/tldr.js#2]
I think TLDR.js should be categorized by objects, and statements (like loops, if, switch, etc.).

For instance, we could have a `STRING.md`, which would represent the `String` object.   It would include information about itself, best practices, prototype, etc.

A caveat to this method is documenting non-object things, as mentioned above, statements.  You'd end up with short files like `IF.md` because statements  typically aren't as robust as objects.

This is just one idea for reorganization.  Lemme know your ideas, or if you want to keep it how it is.

**Comment by whaaaley** [comment]
I would prefer to keep all objects in one file rather than splitting them up. One of the things I don't like about MDN is that there's no place I can't just scroll down a list of everything and get a brief description.

**Comment by jamen** [comment]
Yeah, that's how a lot of styleguides I've seen on GitHub work.  I agree.
