### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by jamen** [JamenMarz/tldr.js#4]
Styleguides should be robust.  "TLDR" makes it sound too simple, and also limits us to the amount of information we can document (or else it pretty much invalidates the name).

In fact, we already have a lot of information that I wouldn't really consider a "TL;DR", because it's still quite a bit of info.

We should brainstorm some new names.  We could kinda make it a play on JavaScript. 

I.e.: decaf.js, caffeine.js, espresso.js, etc.

Or, we could try something else, like "pekoe" (high quality tea)...

**Comment by whaaaley** [comment]
i was already thinking about this when i cloned again. i also think we should drop the dot js too. it's not a library. maybe use a dash instead so we can have other projects in the same vein but with a different suffix.

**Comment by jamen** [comment]
@dustindowell22 Yeah, I'd like to drop `.js` too, and it would be cool to make it a group of style guides.

Perhaps something like "pekoe-javascript" (or just pekoe), "pekoe-sass", etc.  :P

**Comment by whaaaley** [comment]
I just did a thesaurus search for "information" and `lowdown-js` seems nice to me :+1:
